services:
  resto-roulette:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5172:5172"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
